/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OrdemServicoView.java
 *
 * Created on 30/11/2011, 23:35:10
 */
package br.com.infortec.view;

/**
 *
 * @author Adriano
 */
public class OrdemServicoView extends javax.swing.JFrame {

    /** Creates new form OrdemServicoView */
    public OrdemServicoView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jlClienteserviço = new javax.swing.JLabel();
        jlDados_Aparelho_serviço = new javax.swing.JLabel();
        jlData_entrada = new javax.swing.JLabel();
        jlPrevisão_saída = new javax.swing.JLabel();
        jlData_entrega = new javax.swing.JLabel();
        jlDefeito_serviço = new javax.swing.JLabel();
        jtDefeito_serviço = new javax.swing.JTextField();
        jlPreço_serviço = new javax.swing.JLabel();
        jtPreço_serviço = new javax.swing.JTextField();
        jlserviço_idserviço = new javax.swing.JLabel();
        jtserviço_idserviço = new javax.swing.JTextField();
        jlFuncionario_cod_funcionario = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jbimprimir = new javax.swing.JButton();
        jbOk = new javax.swing.JButton();
        jbcancelar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();

        jLabel2.setText("jLabel2");

        setTitle("Ordem de Serviços");

        jlClienteserviço.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlClienteserviço.setText("Cliente:");

        jlDados_Aparelho_serviço.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlDados_Aparelho_serviço.setText("Dados Aparelho:");

        jlData_entrada.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlData_entrada.setText("Data entrada:");

        jlPrevisão_saída.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlPrevisão_saída.setText("Previsão saída:");

        jlData_entrega.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlData_entrega.setText("Data entrega:");

        jlDefeito_serviço.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlDefeito_serviço.setText("Defeito relatado:");

        jtDefeito_serviço.setToolTipText("Defeitos relatados");

        jlPreço_serviço.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlPreço_serviço.setText("Preço:");

        jtPreço_serviço.setToolTipText("Informe o valor do serviço");

        jlserviço_idserviço.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlserviço_idserviço.setText("Serviço Efetuado:");

        jtserviço_idserviço.setToolTipText("Serviço que foi efetuado");
        jtserviço_idserviço.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtserviço_idserviçoActionPerformed(evt);
            }
        });

        jlFuncionario_cod_funcionario.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlFuncionario_cod_funcionario.setText("Funcionário Resposável:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.setToolTipText("Selecione o funcionário");

        jbimprimir.setFont(new java.awt.Font("Tahoma", 1, 12));
        jbimprimir.setText("Imprimir");

        jbOk.setFont(new java.awt.Font("Tahoma", 1, 12));
        jbOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infortec/imagens/salvar32x32.png"))); // NOI18N
        jbOk.setText("Ok");

        jbcancelar.setFont(new java.awt.Font("Tahoma", 1, 12));
        jbcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/infortec/imagens/cancelar32x32.png"))); // NOI18N
        jbcancelar.setText("Cancelar");

        jbVoltar.setFont(new java.awt.Font("Tahoma", 1, 12));
        jbVoltar.setText("Voltar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbVoltar)
                .addGap(35, 35, 35)
                .addComponent(jbimprimir)
                .addGap(39, 39, 39)
                .addComponent(jbcancelar)
                .addGap(36, 36, 36)
                .addComponent(jbOk)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbOk)
                    .addComponent(jbcancelar)
                    .addComponent(jbimprimir)
                    .addComponent(jbVoltar))
                .addContainerGap())
        );

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setToolTipText("Selecione o cliente");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField1.setToolTipText("Informe a data de entrada");

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField2.setToolTipText("Previsão de saída");

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jFormattedTextField3.setToolTipText("Informe a data de saída");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtserviço_idserviço, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                            .addComponent(jtDefeito_serviço, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlPreço_serviço)
                                .addGap(18, 18, 18)
                                .addComponent(jtPreço_serviço, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                                .addComponent(jlFuncionario_cod_funcionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlClienteserviço)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlDados_Aparelho_serviço)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlData_entrada)
                                .addGap(36, 36, 36)
                                .addComponent(jlPrevisão_saída)
                                .addGap(30, 30, 30)
                                .addComponent(jlData_entrega))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlDefeito_serviço)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlserviço_idserviço)
                                .addGap(587, 587, 587))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jlClienteserviço)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlDados_Aparelho_serviço)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlData_entrada)
                    .addComponent(jlPrevisão_saída)
                    .addComponent(jlData_entrega))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlDefeito_serviço)
                .addGap(5, 5, 5)
                .addComponent(jtDefeito_serviço, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlserviço_idserviço)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtserviço_idserviço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFuncionario_cod_funcionario)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlPreço_serviço)
                    .addComponent(jtPreço_serviço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jtserviço_idserviçoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtserviço_idserviçoActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jtserviço_idserviçoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OrdemServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OrdemServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OrdemServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OrdemServicoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new OrdemServicoView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbOk;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JButton jbcancelar;
    private javax.swing.JButton jbimprimir;
    private javax.swing.JLabel jlClienteserviço;
    private javax.swing.JLabel jlDados_Aparelho_serviço;
    private javax.swing.JLabel jlData_entrada;
    private javax.swing.JLabel jlData_entrega;
    private javax.swing.JLabel jlDefeito_serviço;
    private javax.swing.JLabel jlFuncionario_cod_funcionario;
    private javax.swing.JLabel jlPrevisão_saída;
    private javax.swing.JLabel jlPreço_serviço;
    private javax.swing.JLabel jlserviço_idserviço;
    private javax.swing.JTextField jtDefeito_serviço;
    private javax.swing.JTextField jtPreço_serviço;
    private javax.swing.JTextField jtserviço_idserviço;
    // End of variables declaration//GEN-END:variables
}
