/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComprasView.java
 *
 * Created on 22/11/2011, 17:26:06
 */
package br.com.infortec.view;

import br.com.infortec.DAO.EstoqueDAO;
import br.com.infortec.DAO.FuncionarioDAO;
import br.com.infortec.DAO.ItensVendasDAO;
import br.com.infortec.DAO.ProdutoDAO;
import br.com.infortec.DAO.VendasDAO;
import br.com.infortec.bean.Cliente;
import br.com.infortec.bean.Estoque;
import br.com.infortec.bean.Funcionario;
import br.com.infortec.bean.ItensVendas;
import br.com.infortec.bean.Produto;
import br.com.infortec.bean.Vendas;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author Israelly
 */
public class VendasView extends javax.swing.JFrame {

    /** Creates new form ComprasView */
    public VendasView() {
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    int cont = 0;
    public static Cliente clienteImportado = new Cliente();
    //public static Produto produtoimportado = new Produto();
    VendasDAO vendasDAO = new VendasDAO();
    ItensVendas itensVendas = new ItensVendas();
    private int codVendas;
    static JFrame frame;
    ItensVendasDAO itensVendasDAO = new ItensVendasDAO();
    List<ItensVendas> ListaEditItensVendas = itensVendasDAO.consultarItensVendas(codVendas);
    ProdutoDAO produtoDAO = new ProdutoDAO();
    FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
    
    List<Produto> listaBuscaProduto = produtoDAO.listarTodosProdutos();
    //   ItensCompras itensCompras = new ItensCompras(produto, qtde, vlrUnit, vlrTotal, compras);
    int add = 0;
    int[] idItens;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btBuscarCliente = new javax.swing.JButton();
        txtCliente = new javax.swing.JTextField();
        btCadastrarCliente = new javax.swing.JButton();
        btOk = new javax.swing.JButton();
        painelIntensCompras = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtValorUnitario = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable(){

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        qtdTextField = new javax.swing.JTextField();
        painelTotais = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        CustotalTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valordescTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TotalpgTextField = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        painelprodutos = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable(){

            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        jButton4 = new javax.swing.JButton();
        txtQtdeProduto = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compras");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 12));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Vendas");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Cliente:");

        btBuscarCliente.setFont(new java.awt.Font("Tahoma", 1, 12));
        btBuscarCliente.setText("Buscar Cliente");
        btBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarClienteActionPerformed(evt);
            }
        });

        txtCliente.setBackground(new java.awt.Color(255, 255, 204));
        txtCliente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCliente.setToolTipText("Clique para Encontrar um Cliente");

        btCadastrarCliente.setFont(new java.awt.Font("Tahoma", 1, 12));
        btCadastrarCliente.setText("Cadastrar Novo Cliente");
        btCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarClienteActionPerformed(evt);
            }
        });

        btOk.setFont(new java.awt.Font("Tahoma", 1, 12));
        btOk.setText("Ok");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(btBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCadastrarCliente))
                    .addComponent(btOk, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btCadastrarCliente)
                    .addComponent(btBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btOk)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelIntensCompras.setVisible(false);
        painelIntensCompras.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelIntensCompras.setFont(new java.awt.Font("Tahoma", 1, 12));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Qtde:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Produto:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("Ítens Vendas");

        txtProduto.setBackground(new java.awt.Color(255, 255, 204));
        txtProduto.setEditable(false);
        txtProduto.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtProduto.setToolTipText("Informe o nome do produto");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Valor unitário:");

        txtValorUnitario.setBackground(new java.awt.Color(255, 255, 204));
        txtValorUnitario.setEditable(false);
        txtValorUnitario.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtValorUnitario.setToolTipText("Informe o valor unitário");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setText("Buscar Produto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        table.setBackground(new java.awt.Color(255, 255, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(table);

        qtdTextField.setBackground(new java.awt.Color(255, 255, 204));
        qtdTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        qtdTextField.setToolTipText("Informe a quantidade de ítens");
        qtdTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                qtdTextFieldFocusLost(evt);
            }
        });

        javax.swing.GroupLayout painelIntensComprasLayout = new javax.swing.GroupLayout(painelIntensCompras);
        painelIntensCompras.setLayout(painelIntensComprasLayout);
        painelIntensComprasLayout.setHorizontalGroup(
            painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIntensComprasLayout.createSequentialGroup()
                .addGroup(painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelIntensComprasLayout.createSequentialGroup()
                        .addGroup(painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelIntensComprasLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelIntensComprasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelIntensComprasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(txtValorUnitario, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelIntensComprasLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel6)))
                .addContainerGap())
        );
        painelIntensComprasLayout.setVerticalGroup(
            painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelIntensComprasLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelIntensComprasLayout.createSequentialGroup()
                        .addGroup(painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelIntensComprasLayout.createSequentialGroup()
                        .addGroup(painelIntensComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addGap(27, 27, 27)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelTotais.setVisible(false);
        painelTotais.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Custo Total:");

        CustotalTextField.setBackground(new java.awt.Color(255, 255, 204));
        CustotalTextField.setFont(new java.awt.Font("Tahoma", 1, 12));
        CustotalTextField.setText("0");
        CustotalTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustotalTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Desconto:");

        valordescTextField1.setFont(new java.awt.Font("Tahoma", 1, 12));
        valordescTextField1.setText("0");
        valordescTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                valordescTextField1FocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Total a Pagar:");

        TotalpgTextField.setBackground(new java.awt.Color(255, 255, 204));
        TotalpgTextField.setFont(new java.awt.Font("Tahoma", 1, 12));
        TotalpgTextField.setText("0");
        TotalpgTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalpgTextFieldActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton5.setText("Excluir Produto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton6.setText("Imprimir Nota");

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton7.setText("Salvar Venda");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel10.setText("%");

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton8.setText("Nova venda");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelTotaisLayout = new javax.swing.GroupLayout(painelTotais);
        painelTotais.setLayout(painelTotaisLayout);
        painelTotaisLayout.setHorizontalGroup(
            painelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTotaisLayout.createSequentialGroup()
                .addGroup(painelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(CustotalTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(TotalpgTextField)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelTotaisLayout.createSequentialGroup()
                            .addComponent(valordescTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel10)))
                    .addGroup(painelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING, 0, 0, Short.MAX_VALUE)
                        .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTotaisLayout.setVerticalGroup(
            painelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTotaisLayout.createSequentialGroup()
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelTotaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valordescTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TotalpgTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelprodutos.setVisible(false);
        painelprodutos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tableProdutos.setBackground(new java.awt.Color(255, 255, 204));
        tableProdutos.setModel(tabelaProdutoModel(listaBuscaProduto));
        jScrollPane4.setViewportView(tableProdutos);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton4.setText("Adicionar à Venda");
        jButton4.setToolTipText("Adicionar à Venda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtQtdeProduto.setFont(new java.awt.Font("Tahoma", 1, 12));
        txtQtdeProduto.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        txtQtdeProduto.setOpaque(false);

        javax.swing.GroupLayout painelprodutosLayout = new javax.swing.GroupLayout(painelprodutos);
        painelprodutos.setLayout(painelprodutosLayout);
        painelprodutosLayout.setHorizontalGroup(
            painelprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelprodutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelprodutosLayout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtdeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelprodutosLayout.setVerticalGroup(
            painelprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelprodutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(painelprodutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(txtQtdeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel11.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(painelIntensCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(painelTotais, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(painelprodutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelprodutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelTotais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelIntensCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TotalpgTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalpgTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalpgTextFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        painelprodutos.setVisible(true);
        VendasView.this.setSize(1100, 500);

        ////if(produtosComprados.isEmpty()){
////produtosComprados.add(itensCompra);
////}     
//      String [] args = new String[1];
//      args[0] = "Localizar Produtos";
//      BuscaProdutoView.main(args);
//      BuscaProdutoView.setCodCompra(codCompras);

    }//GEN-LAST:event_jButton1ActionPerformed

private void btBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarClienteActionPerformed
    String[] titulo = {"Busca de Clientes"};
    BuscaClienteView.main(titulo);
}//GEN-LAST:event_btBuscarClienteActionPerformed

private void btCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarClienteActionPerformed
    String[] titulo = {"Cadastro de Clientes"};
    ClienteView.main(titulo);

}//GEN-LAST:event_btCadastrarClienteActionPerformed

private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
    Funcionario funcionario = funcionarioDAO.consultarFuncionario(2);
    Vendas vendasCab = new Vendas(clienteImportado, funcionario);
    codVendas = vendasDAO.inserirVendasCab(vendasCab);
    painelIntensCompras.setVisible(true);
    painelTotais.setVisible(true);
    table.setModel(tabelaModel(ListaEditItensVendas, codVendas));
    VendasView.this.setSize(700, 500);

}//GEN-LAST:event_btOkActionPerformed
    String QuantidadeDeprodutos;
    Vendas venda = vendasDAO.consultarVendas(codVendas);
    Produto produto = new Produto();
private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    produto = listaBuscaProduto.get(tableProdutos.getSelectedRow());
    setTxtProduto(produto.getNome());
    setTxtValorUnitario(produto.getValorCompra());
    qtdTextField.setText(String.valueOf(txtQtdeProduto.getValue()));
    QuantidadeDeprodutos = getTxtQtdeProduto().getValue().toString();
    addProduto();
    
    CustotalTextField.setText(String.valueOf(calculaTotal()));
    TotalpgTextField.setText(String.valueOf(calculaTotal()-(totalPagar * (Double.valueOf(valordescTextField1.getText()) / 100))));
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    removeProduto(table.getSelectedRow());
    calculaTotal();
}//GEN-LAST:event_jButton5ActionPerformed

private void valordescTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_valordescTextField1FocusLost
    Double totalGeral = totalPagar - (totalPagar * (Double.valueOf(valordescTextField1.getText()) / 100));
    TotalpgTextField.setText(String.valueOf(totalGeral));
}//GEN-LAST:event_valordescTextField1FocusLost

private void CustotalTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustotalTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_CustotalTextFieldActionPerformed

private void qtdTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_qtdTextFieldFocusLost
    table.setValueAt(qtdTextField.getText(), table.getSelectedRow(), 2);
    ListaEditItensVendas.get(table.getSelectedRow()).setRqtde((Double.valueOf(qtdTextField.getText())));
    calculaTotal();
    table.setModel(tabelaModel(ListaEditItensVendas, codVendas));
    CustotalTextField.setText(String.valueOf(totalPagar));
}//GEN-LAST:event_qtdTextFieldFocusLost
Estoque estoque;
private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    EstoqueDAO estoqueDAO = new EstoqueDAO();
    idItens = itensVendasDAO.inserirItensVendas(ListaEditItensVendas);
    
    
    
//    for (int i = 0; i < idItens.length; i++) {
//        ItensVendas itemVendido = itensVendasDAO.consultarItem(idItens[i]);
//        Produto produto1 = produtoDAO.consultarProduto(itemVendido.getProduto().getCodProduto());
//       Estoque  estoque = new Estoque(produto1, itemVendido.getRqtde());
//        System.out.println("++++++++");
//        estoqueDAO.alterarEstoqueVenda(estoque);
 //   }
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
   this.main(null);
    this.dispose();
}//GEN-LAST:event_jButton8ActionPerformed
    public void addProduto() {
        ItensVendas itensVendas = new ItensVendas(Double.valueOf(QuantidadeDeprodutos), produto.getValorVenda(), produto.getValorCompra() * Double.valueOf(QuantidadeDeprodutos), venda, produto);
        ListaEditItensVendas.add(itensVendas);
        table.setModel(tabelaModel(ListaEditItensVendas, codVendas));
        add++;
    }
    Double totalPagar = 0.0;

    public void removeProduto(int index) {
        ListaEditItensVendas.remove(index);
        table.setModel(tabelaModel(ListaEditItensVendas, codVendas));
        calculaTotal();
        CustotalTextField.setText(String.valueOf(totalPagar));
    }

    public Double calculaTotal() {
        totalPagar = 0.0;

        for (ItensVendas totalItens : ListaEditItensVendas) {
            totalPagar += (totalItens.getVlrTotal());
        }
        return totalPagar;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VendasView().setVisible(true);


            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustotalTextField;
    private javax.swing.JTextField TotalpgTextField;
    private javax.swing.JButton btBuscarCliente;
    private javax.swing.JButton btCadastrarCliente;
    private javax.swing.JButton btOk;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    private javax.swing.JPanel painelIntensCompras;
    private javax.swing.JPanel painelTotais;
    private javax.swing.JPanel painelprodutos;
    private javax.swing.JTextField qtdTextField;
    public javax.swing.JTable table;
    private javax.swing.JTable tableProdutos;
    private static javax.swing.JTextField txtCliente;
    private static javax.swing.JTextField txtProduto;
    private javax.swing.JSpinner txtQtdeProduto;
    private javax.swing.JTextField txtValorUnitario;
    private javax.swing.JTextField valordescTextField1;
    // End of variables declaration//GEN-END:variables

    public TableModel tabelaModel(List<ItensVendas> listaItensVendas, int idVendas) {
        int n = 0;
        JTable table1;
        Vendas venda1 = vendasDAO.consultarVendas(idVendas);

        //  listaItensCompras = itensComprasDAO.consultarItensCompras(idCompras);
        Object[][] data = new Object[listaItensVendas.size()][6];
        String[] columnNames = {"Cod da Venda ", "Produto", "Qtde", "valor Unitário", "Valor total"};

        for (ItensVendas itensVendas1 : listaItensVendas) {
            itensVendas1.setVendas(venda1);
            data[n][0] = itensVendas1.getVendas().getCod();
            data[n][1] = itensVendas1.getProduto().getNome();
            data[n][2] = itensVendas1.getRqtde();
            data[n][3] = itensVendas1.getProduto().getValorCompra();
            data[n][4] = itensVendas1.getVlrTotal();


            n++;
        }

        table1 = new JTable(data, columnNames);
        table1.setPreferredScrollableViewportSize(new Dimension(500, 300));
        table1.setFillsViewportHeight(true);
        table1.getColumnModel().getColumn(0).setPreferredWidth(100);
        table1.getColumnModel().getColumn(1).setPreferredWidth(300);
        table1.getColumnModel().getColumn(2).setPreferredWidth(300);
        javax.swing.table.TableModel model = table1.getModel();



        table.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                //
                editarLinha();
                // }
            }
        });
        return model;
    }

    public void editarLinha() {
        int index = table.getSelectedRow();

        txtProduto.setText(String.valueOf(table.getValueAt(table.getSelectedRow(), 1)));
        qtdTextField.setText(String.valueOf(table.getValueAt(table.getSelectedRow(), 2)));
        txtValorUnitario.setText(String.valueOf(table.getValueAt(table.getSelectedRow(), 3)));
    }

    public javax.swing.JTextField getTxtProduto() {
        return txtProduto;
    }

    public static void setTxtProduto(String NomeProduto) {
        txtProduto.setText(NomeProduto);
    }

    public static javax.swing.JTextField getTxtFornecedor() {
        return txtCliente;
    }

    public static void setTxtCliente(String nomeCliente) {
        txtCliente.setText(nomeCliente);
    }

    public void setTxtValorUnitario(double valorUnitario) {
        this.txtValorUnitario.setText(String.valueOf(valorUnitario));
    }

    public javax.swing.JSpinner getTxtQtdeProduto() {
        return txtQtdeProduto;
    }

    public void setTxtQtdeProduto(javax.swing.JSpinner txtQtdeProduto) {
        this.txtQtdeProduto = txtQtdeProduto;
    }

    public TableModel tabelaProdutoModel(List<Produto> listaProdutos) {
        int n = 0;
        JTable table1;
        listaProdutos = produtoDAO.listarTodosProdutos();
        Object[][] data = new Object[listaProdutos.size()][10];
        String[] columnNames = {"cod Produto", "Nome", "Descrição", "Valor Compra", "Valor Venda", "Estoque", "Localização", "Fornecedor", "Categoria", "Margem Lucro"};

        for (Produto produtos : listaProdutos) {
            data[n][0] = produtos.getCodProduto();
            data[n][1] = produtos.getNome();
            data[n][2] = produtos.getDescricao();
            data[n][3] = produtos.getValorCompra();
            data[n][4] = produtos.getValorVenda();
            data[n][5] = produtos.getEstoque();
            data[n][6] = produtos.getLocalizacao();
            data[n][7] = produtos.getFornecedor().getNome();
            data[n][8] = produtos.getCategoria().getnomeCategoria();
            data[n][9] = produtos.getMargemLucro();

            n++;
        }

        table1 = new JTable(data, columnNames);
        table1.setPreferredScrollableViewportSize(new Dimension(500, 300));
        table1.setFillsViewportHeight(true);
        table1.getColumnModel().getColumn(0).setPreferredWidth(100);
        table1.getColumnModel().getColumn(1).setPreferredWidth(300);
        table1.getColumnModel().getColumn(2).setPreferredWidth(300);
        javax.swing.table.TableModel model = table1.getModel();



//        table.addMouseListener(new MouseAdapter() {

//            public void mouseClicked(MouseEvent e) {
//                if (cont % 2 == 1) {
//                    editarLinha();
//                }
//            }
//        });
        return model;//adiciona um modela a tabela
    }
}
//    public void editarLinha() {
//        int index = table.getSelectedRow();
//        nomeProdutoField.setText((String) table.getValueAt(table.getSelectedRow(), 1));
//        descricaoProdutoField.setText((String) table.getValueAt(table.getSelectedRow(), 2));
//        valorCompraProdutoField.setText((String) table.getValueAt(table.getSelectedRow(), 3).toString());
//        valorVendaProdutoField.setText(table.getValueAt(table.getSelectedRow(), 4).toString());
//        estoqueField.setText(table.getValueAt(table.getSelectedRow(), 5).toString());
//        localizacaoProdutoField.setText((String) table.getValueAt(table.getSelectedRow(), 6));
//        FornecedorComboBox.setSelectedItem((String) table.getValueAt(table.getSelectedRow(), 7));
//        categoriaComboBox.setSelectedItem((String) table.getValueAt(table.getSelectedRow(), 8));
//        MargemLucroTextField.setText(table.getValueAt(table.getSelectedRow(), 9).toString());
//    }
//}
